/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenturesRouteImport } from './routes/ventures'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as JewelsRouteImport } from './routes/jewels'
import { Route as IndexRouteImport } from './routes/index'

const VenturesRoute = VenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelsRoute = JewelsRouteImport.update({
  id: '/jewels',
  path: '/jewels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jewels': typeof JewelsRoute
  '/spaces': typeof SpacesRoute
  '/ventures': typeof VenturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jewels': typeof JewelsRoute
  '/spaces': typeof SpacesRoute
  '/ventures': typeof VenturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jewels': typeof JewelsRoute
  '/spaces': typeof SpacesRoute
  '/ventures': typeof VenturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jewels' | '/spaces' | '/ventures'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jewels' | '/spaces' | '/ventures'
  id: '__root__' | '/' | '/jewels' | '/spaces' | '/ventures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JewelsRoute: typeof JewelsRoute
  SpacesRoute: typeof SpacesRoute
  VenturesRoute: typeof VenturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventures': {
      id: '/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof VenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewels': {
      id: '/jewels'
      path: '/jewels'
      fullPath: '/jewels'
      preLoaderRoute: typeof JewelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JewelsRoute: JewelsRoute,
  SpacesRoute: SpacesRoute,
  VenturesRoute: VenturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
